FROM node:10
WORKDIR /app

# FROM node:lts-alpine

# WORKDIR /app

# # Configure apt and install packages
# RUN apk update \
#     && apk upgrade \
#     #
#     # add git and needed tools
#     && apk add --no-cache \
#     # uncomment if gcc needed for native code
#         # build-dependencies \
#         # build-base \
#         # gcc \
#         # wget \
#         openssh-client \
#         ca-certificates \
#         git \
#         bash \
#     #
#     # Install eslint globally
#     && npm install -g eslint \
#     # cleanup
#     && rm -rf /var/lib/apt/lists/* \
#     && rm /var/cache/apk/*
    